{% set name = "vprof" %}
{% set version = "0.37.4" %}
{% set sha256 = "83fc52944a00cb488e0297e90f8ff4ac1d4c8b39c30563879058a1455005ddc4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: v{{ version }}.tar.gz
  url: https://github.com/nvdv/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  # noarch: python
  number: 0
  script: python setup.py deps_install && python setup.py build_ui && python setup.py install && python setup.py test && python setup.py e2e_test

requirements:
  build:
    - python
    - pip
    - nodejs
  run:
    - python

test:
  imports:
    - vprof

about:
  home: https://github.com/nvdv/vprof
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Visual profiler for Python'

  description: |
    vprof is a Python package providing rich and interactive visualizations for various Python 
    program characteristics such as running time and memory usage. It supports Python 2.7, 
    Python 3.4+ and distributed under BSD license.
  doc_url: https://github.com/nvdv/vprof
  dev_url: https://github.com/nvdv/vprof

extra:
  recipe-maintainers:
    - alen12345
