{% set name = "fltk" %}
{% set version = "1.3.4" %}
{% set longversion = "1.3.4-2" %}
{% set md5 = "69128be72365cbedd1d380739f0164e3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ longversion }}-source.tar.gz
  url: http://fltk.org/pub/{{ name }}/{{ version }}/{{ name }}-{{ longversion }}-source.tar.bz2
  md5: {{ md5 }}
  patches:
    - macros.patch

build:
  number: 0
  features:
    - vc9   # [win and py27]
    - vc14  # [win and (py35 or py36)]

requirements:
  build:
    - toolchain
    - cmake
    - zlib 1.2.11
    - jpeg 9*
    - libpng >=1.6.32,<1.6.35
    - vc 9   # [win and py27]
    - vc 14  # [win and (py35 or py36)]
  run:
    - zlib 1.2.11
    - jpeg 9*
    - libpng >=1.6.32,<1.6.35
    - vc 9   # [win and py27]
    - vc 14  # [win and (py35 or py36)]

test:
  commands:
    - echo "Tests have already been executed after compilation."
    - conda inspect linkages -p $PREFIX fltk  # [not win]
    - conda inspect objects -p $PREFIX fltk  # [osx]

about:
  home: http://www.fltk.org/
  license: LGPL-2.0
  license_family: LGPL
  license_file: COPYING
  summary: 'The Fast Light Tool Kit ("FLTK", pronounced "fulltick") is a cross-platform C++ GUI toolkit'

  description: |
    FLTK (pronounced "fulltick") is a cross-platform C++ GUI toolkit for
    UNIX/Linux (X11), Microsoft Windows, and MacOS X. FLTK provides
    modern GUI functionality without the bloat and supports 3D graphics via
    OpenGL and its built-in GLUT emulation.

    FLTK is designed to be small and modular enough to be statically
    linked, but works fine as a shared library. FLTK also includes an
    excellent UI builder called FLUID that can be used to create
    applications in minutes.
  doc_url: http://www.fltk.org/documentation.php
  dev_url: http://www.fltk.org/roadmap.php

extra:
  recipe-maintainers:
    - guyer
    - alen12345
