{% set name = "gmsh" %}
{% set version = "3.0.6" %}
{% set sha256 = "9700bcc440d7a6b16a49cbfcdcdc31db33efe60e1f5113774316b6fa4186987b" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}-source.tar.gz
  url: http://gmsh.info/src/{{ name }}-{{ version }}-source.tgz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  # remove the tests of OpenCascade and fltk until we implement them in conda-forge
  script: sed -i '1919i \ \ list(REMOVE_ITEM TESTFILES "${CMAKE_SOURCE_DIR}/tutorial/t16.geo")' CMakeLists.txt && sed -i '1919i \ \ list(REMOVE_ITEM TESTFILES "${CMAKE_SOURCE_DIR}/demos/post_processing/lowmem-anim.geo")' CMakeLists.txt && mkdir build && cd build && cmake .. -DCMAKE_INSTALL_PREFIX=$PREFIX && make && make test ARGS="-V" && make install

requirements:
  build:
    - python
    - toolchain
    - cmake
    - gcc
    - sed
    - openblas
    - lapack
    - libpng
    - jpeg
    - gmp
  run:
    - python
    - gcc
    - gmp
    - openblas
    - lapack
    - libpng
    - jpeg

test:
  commands:
    - gmsh -help

about:
  home: http://gmsh.info/
  license: GPL-2.0
  license_family: GPL
  license_file: LICENSE.txt
  summary: 'This is Gmsh, an automatic three-dimensional finite element mesh generator.'

  description: |
    This is Gmsh, an automatic three-dimensional finite element mesh generator with
    built-in pre- and post-processing facilities.
  doc_url: http://gmsh.info/doc/texinfo/gmsh.html
  dev_url: https://gitlab.onelab.info/gmsh/gmsh

extra:
  recipe-maintainers:
    - alen12345
